[workspace]
resolver = "2"
members = ["src-tauri", "daemon"]

[workspace.package]
authors = ["thep0y"]
version = "0.1.13"
# homepage = ""
repository = "https://github.com/dwall-rs/dwall"
license = "AGPL-3.0"
edition = "2021"

[workspace.dependencies]
dirs = "6"
thiserror = { version = "2", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
serde_json = "1"
tracing = { version = "0", default-features = false, features = [
  "log",
  "release_max_level_info",
] }
tracing-subscriber = { version = "0", default-features = false, features = [
  "fmt",
  'time',
  "local-time",
  'env-filter',
  'json',
] }
tokio = { version = "1", default-features = false }
windows = { version = "0.60", default-features = false }

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
