[workspace]
resolver = "2"
members = ["src-tauri", "daemon"]

[workspace.package]
authors = ["thep0y"]
version = "0.1.0"
# homepage = ""
repository = "https://github.com/dwall-rs/dwall"
# license = "Apache-2.0 OR MIT"
edition = "2021"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
incremental = false
opt-level = "s"
strip = true
