//! Color scheme decision engine with hysteresis

use time::OffsetDateTime;

use crate::domain::{
    time::solar_calculator::SolarPosition,
    visual::color_scheme::{
        ColorScheme, DaylightState, ThresholdConfig,
        constants::{WAKING_HOUR_END, WAKING_HOUR_START, WHITE_NIGHT_AMPLITUDE_MARGIN},
    },
};

/// Determine the color scheme to apply based on solar altitude and hysteresis
///
/// # Decision flow
///
/// ```text
///                    ┌─────────────────────┐
///                    │  DaylightState pre   │
///                    └──────────┬──────────┘
///              ┌────────────────┼─────────────────┐
///        MidnightSun       PolarNight          WhiteNight
///              │                │                  │
///           Light         Clock fallback     Dynamic midpoint hysteresis
///                               │                  │
///                     is_waking_hours?       midpoint ± forced dead zone
///                      /        \
///                   Light      Dark
///
///                    ┌──────── Normal ────────┐
///                    │  Schmitt trigger hysteresis  │
///                    │                        │
///            Currently Dark            Currently Light
///          switch_point = base+band   switch_point = base-band
///              altitude > sp?             altitude < sp?
///               /      \                  /       \
///            Light     Dark            Dark      Light
///           (switch)  (keep)         (switch)   (keep)
/// └──────────────────────────────────────────────────────────┘
/// ```
///
/// # Parameters
/// - `solar_position`: precomputed solar position; `.altitude()` returns the
///   apparent altitude including refraction correction
/// - `current_scheme`: current color scheme (the key state for hysteresis)
/// - `config`: dynamic threshold configuration, generated by [`ThresholdConfig::from_position`]
/// - `local_time`: local time including timezone offset, used for polar night clock fallback
/// - `daylight_state`: the extreme daylight state for the day, should be computed
///   once per day by the caller and passed in cached
///
/// # Note
/// This function does not apply any additional refraction correction to
/// `solar_position.altitude()` — `SolarPosition`'s internal `altitude_from_context`
/// already applies the Bennett formula correction.
pub(crate) fn determine_color_scheme_with_hysteresis(
    solar_position: &SolarPosition,
    current_scheme: &ColorScheme,
    config: &ThresholdConfig,
    local_time: &OffsetDateTime,
    daylight_state: &DaylightState,
) -> ColorScheme {
    // ── Phase 1: Extreme state pre‑processing ───────────────────────────────────
    //
    // All three extreme states short-circuit here and do not enter the main
    // hysteresis logic, ensuring that the main logic only handles the normal
    // case where the altitude fully crosses the threshold.
    match daylight_state {
        // Midnight sun: sun is above the threshold all day, force light
        DaylightState::MidnightSun => return ColorScheme::Light,

        // Polar night: sun is below the threshold all day, astronomical
        // determination is meaningless. Fall back to local clock:
        // light during waking hours, dark otherwise.
        DaylightState::PolarNight => {
            let hour = local_time.hour();
            return if (WAKING_HOUR_START..WAKING_HOUR_END).contains(&hour) {
                ColorScheme::Light
            } else {
                ColorScheme::Dark
            };
        }

        // White night: altitude oscillates slightly around the threshold,
        // use dynamic midpoint + forced wide dead zone
        //
        // Dead zone half-width = WHITE_NIGHT_AMPLITUDE_MARGIN / 2 = 2°
        // 4× wider than the standard HYSTERESIS_BAND (0.5°), specifically to
        // combat the high-frequency jitter of white nights.
        // During white nights the relationship between local time and altitude
        // direction is unreliable; time-based assistance is not used here —
        // rely solely on the midpoint threshold + wide dead zone.
        DaylightState::WhiteNight {
            min_altitude,
            max_altitude,
        } => {
            let midpoint = (min_altitude + max_altitude) / 2.0;
            let half_band = WHITE_NIGHT_AMPLITUDE_MARGIN / 2.0; // 2.0°
            let altitude = solar_position.altitude();

            return if altitude >= midpoint + half_band {
                ColorScheme::Light
            } else if altitude < midpoint - half_band {
                ColorScheme::Dark
            } else {
                // Inside the dead zone: keep the current state (inertia principle)
                *current_scheme
            };
        }

        // Normal case: proceed to the Schmitt trigger logic below
        DaylightState::Normal => {}
    }

    // ── Phase 2: Schmitt trigger hysteresis (executed only for Normal state) ───
    //
    // Choose different switching points depending on the current state:
    //   - Currently Dark  → need a higher altitude to switch to Light (higher bar when rising)
    //   - Currently Light → need a lower altitude to switch to Dark (lower bar when falling)
    //
    // This forms a dead zone of width 2 × HYSTERESIS_BAND:
    //   Dark  → Light: altitude must exceed base_threshold + HYSTERESIS_BAND
    //   Light → Dark : altitude must fall below base_threshold - HYSTERESIS_BAND
    //
    // Any crossing within the dead zone is ignored; the current state is preserved.
    let altitude = solar_position.altitude();

    let switch_point = match current_scheme {
        ColorScheme::Dark => config.light_switch_point(),
        ColorScheme::Light => config.dark_switch_point(),
    };

    if altitude > switch_point {
        ColorScheme::Light
    } else {
        ColorScheme::Dark
    }
}

#[cfg(test)]
mod tests {
    use time::Month;

    use super::*;

    fn make_config(base: f64) -> ThresholdConfig {
        ThresholdConfig {
            base_threshold: base,
            hysteresis_band: 0.5,
        }
    }

    // ── Schmitt trigger hysteresis ──────────────────────────────────────────────

    #[test]
    fn schmitt_dark_to_light_requires_crossing_upper_point() {
        let config = make_config(-6.0);
        // Rising switch point = -6.0 + 0.5 = -5.5
        // altitude -5.6°: below -5.5°, currently Dark → should remain Dark
        assert_altitude_scheme(-5.6, ColorScheme::Dark, &config, ColorScheme::Dark);
        // altitude -5.4°: above -5.5°, currently Dark → should switch to Light
        assert_altitude_scheme(-5.4, ColorScheme::Dark, &config, ColorScheme::Light);
    }

    #[test]
    fn schmitt_light_to_dark_requires_crossing_lower_point() {
        let config = make_config(-6.0);
        // Falling switch point = -6.0 - 0.5 = -6.5
        // altitude -6.4°: above -6.5°, currently Light → should remain Light
        assert_altitude_scheme(-6.4, ColorScheme::Light, &config, ColorScheme::Light);
        // altitude -6.6°: below -6.5°, currently Light → should switch to Dark
        assert_altitude_scheme(-6.6, ColorScheme::Light, &config, ColorScheme::Dark);
    }

    #[test]
    fn hysteresis_band_prevents_oscillation_in_dead_zone() {
        let config = make_config(-6.0);
        // Dead zone: (-6.5°, -5.5°)
        // Regardless of current state, inside the dead zone the state should be kept
        for &alt in &[-6.4, -6.0, -5.6] {
            assert_altitude_scheme(alt, ColorScheme::Light, &config, ColorScheme::Light);
            assert_altitude_scheme(alt, ColorScheme::Dark, &config, ColorScheme::Dark);
        }
    }

    // ── Extreme states ──────────────────────────────────────────────────────

    #[test]
    fn midnight_sun_always_returns_light() {
        let config = make_config(-6.0);
        let state = DaylightState::MidnightSun;
        // Regardless of current state, midnight sun forces Light
        for current in [ColorScheme::Light, ColorScheme::Dark] {
            let result = call_with_state(-5.0, &current, &config, 14, &state);
            assert_eq!(result, ColorScheme::Light);
        }
    }

    #[test]
    fn polar_night_follows_waking_hours() {
        let config = make_config(-6.0);
        let state = DaylightState::PolarNight;
        // Within waking hours (10 o'clock) → Light
        assert_eq!(
            call_with_state(-30.0, &ColorScheme::Dark, &config, 10, &state),
            ColorScheme::Light
        );
        // Late night (23 o'clock) → Dark
        assert_eq!(
            call_with_state(-30.0, &ColorScheme::Light, &config, 23, &state),
            ColorScheme::Dark
        );
    }

    #[test]
    fn white_night_uses_midpoint_with_wide_band() {
        // min=-7°, max=-5°, midpoint=-6°, half-band=2°
        // To switch to Light need >= -4°, to switch to Dark need < -8°
        let config = make_config(-6.0);
        let state = DaylightState::WhiteNight {
            min_altitude: -7.0,
            max_altitude: -5.0,
        };

        // -3.9° (> -4.0°) → Light
        assert_eq!(
            call_with_state(-3.9, &ColorScheme::Dark, &config, 12, &state),
            ColorScheme::Light
        );
        // -8.1° (< -8.0°) → Dark
        assert_eq!(
            call_with_state(-8.1, &ColorScheme::Light, &config, 12, &state),
            ColorScheme::Dark
        );
        // -6.0° (inside dead zone) → keep current
        assert_eq!(
            call_with_state(-6.0, &ColorScheme::Light, &config, 12, &state),
            ColorScheme::Light
        );
        assert_eq!(
            call_with_state(-6.0, &ColorScheme::Dark, &config, 12, &state),
            ColorScheme::Dark
        );
    }

    // ── Helpers ──────────────────────────────────────────────────────

    /// Directly test the main logic using a given altitude (bypassing SolarPosition)
    fn assert_altitude_scheme(
        altitude: f64,
        current: ColorScheme,
        config: &ThresholdConfig,
        expected: ColorScheme,
    ) {
        let result = call_with_state(altitude, &current, config, 12, &DaylightState::Normal);
        assert_eq!(
            result, expected,
            "altitude={altitude}, current={current:?} → expected {expected:?}, got {result:?}"
        );
    }

    fn call_with_state(
        altitude: f64,
        current: &ColorScheme,
        config: &ThresholdConfig,
        hour: u8,
        state: &DaylightState,
    ) -> ColorScheme {
        mock_determine(altitude, current, config, hour, state)
    }

    /// Extract the main function logic into a pure function accepting a raw altitude,
    /// convenient for unit testing
    ///
    /// Identical logic to `determine_color_scheme_with_hysteresis`,
    /// only replacing `solar_position.altitude()` with the directly passed `altitude`.
    fn mock_determine(
        altitude: f64,
        current_scheme: &ColorScheme,
        config: &ThresholdConfig,
        hour: u8,
        daylight_state: &DaylightState,
    ) -> ColorScheme {
        match daylight_state {
            DaylightState::MidnightSun => return ColorScheme::Light,
            DaylightState::PolarNight => {
                return if (WAKING_HOUR_START..WAKING_HOUR_END).contains(&hour) {
                    ColorScheme::Light
                } else {
                    ColorScheme::Dark
                };
            }
            DaylightState::WhiteNight {
                min_altitude,
                max_altitude,
            } => {
                let midpoint = (min_altitude + max_altitude) / 2.0;
                let half_band = WHITE_NIGHT_AMPLITUDE_MARGIN / 2.0;
                return if altitude >= midpoint + half_band {
                    ColorScheme::Light
                } else if altitude < midpoint - half_band {
                    ColorScheme::Dark
                } else {
                    *current_scheme
                };
            }
            DaylightState::Normal => {}
        }

        let switch_point = match current_scheme {
            ColorScheme::Dark => config.light_switch_point(),
            ColorScheme::Light => config.dark_switch_point(),
        };

        if altitude > switch_point {
            ColorScheme::Light
        } else {
            ColorScheme::Dark
        }
    }

    // ── Geographic Integration Tests ──────────────────────────────────────────

    fn threshold(lat: f64, lon: f64) -> ThresholdConfig {
        ThresholdConfig::from_position(&crate::Position::from_raw_position(lat, lon, 0.))
    }

    fn solar_position(position: &crate::Position, local: OffsetDateTime) -> SolarPosition {
        let utc = local.utc().unwrap();
        SolarPosition::new(position, &utc)
    }

    fn test_location(
        lat: f64,
        lon: f64,
        year: u16,
        month: Month,
        day: u8,
        offset: &str,
        cases: &[((u8, u8, u8), ColorScheme)],
    ) {
        let config = threshold(lat, lon);
        for &((hour, minute, second), expected) in cases {
            let time = OffsetDateTime::new(
                year,
                month,
                day,
                hour,
                minute,
                second,
                offset.parse().unwrap(),
            )
            .unwrap();
            let position = crate::Position::from_raw_position(lat, lon, 0.);
            let sun = solar_position(&position, time);
            let daylight_state = DaylightState::detect(&position, time.date(), &config);
            let actual = determine_color_scheme_with_hysteresis(
                &sun,
                &ColorScheme::Dark, // initial scheme set to Dark; does not affect core logic (except hysteresis, tests use fixed initial value)
                &config,
                &time,
                &daylight_state,
            );
            assert_eq!(
                actual, expected,
                "Location ({lat}, {lon}) at {time}: expected {expected:?}, got {actual:?}"
            );
        }
    }

    #[test]
    fn test_huocheng_midday_night() {
        // Huocheng, Xinjiang, China
        test_location(
            44.3037058,
            80.9801647,
            2026,
            Month::May,
            15,
            "+08:00",
            &[
                ((6, 30, 0), ColorScheme::Dark),  // before sunrise, should be Dark
                ((7, 15, 0), ColorScheme::Light), // after sunrise, should be Light
                ((12, 0, 0), ColorScheme::Light), // noon, should be Light
                ((21, 0, 0), ColorScheme::Light), // before sunset, should be Light
                ((22, 40, 0), ColorScheme::Dark), // after sunset, should be Dark
                ((3, 0, 0), ColorScheme::Dark),   // late night, should be Dark
            ],
        );
    }

    #[test]
    fn test_greenland_midday_night() {
        // Kujalleq, Greenland
        test_location(
            61.,
            -45.,
            2026,
            Month::January,
            1,
            "-01:00",
            &[
                ((10, 00, 0), ColorScheme::Dark),  // before sunrise, should be Dark
                ((10, 45, 0), ColorScheme::Light), // after sunrise, should be Light
                ((12, 0, 0), ColorScheme::Light),  // noon, should be Light
                ((15, 0, 0), ColorScheme::Light),  // before sunset, should be Light
                ((18, 10, 0), ColorScheme::Dark), // after sunset, larger hysteresis at high latitudes
                ((23, 0, 0), ColorScheme::Dark),  // late night, should be Dark
            ],
        );
    }

    #[test]
    fn test_iceland_midday_night() {
        // Hornstrandir, Iceland
        test_location(
            66.3617958,
            -22.4390253,
            2026,
            Month::March,
            1,
            "+00:00",
            &[
                ((7, 30, 0), ColorScheme::Dark),   // before sunrise, should be Dark
                ((9, 00, 0), ColorScheme::Light),  // after sunrise, should be Light
                ((12, 0, 0), ColorScheme::Light),  // noon, should be Light
                ((18, 30, 0), ColorScheme::Light), // before sunset, should be Light
                ((18, 50, 0), ColorScheme::Light), // after sunset, should be Dark
                ((23, 0, 0), ColorScheme::Dark),   // late night, should be Dark
            ],
        );
    }

    #[test]
    fn test_paris_midday_night() {
        // 9th arrondissement of Paris, Île-de-France, France
        test_location(
            48.8728329,
            2.3281715,
            2026,
            Month::May,
            1,
            "+02:00",
            &[
                ((5, 40, 0), ColorScheme::Dark),   // before sunrise, should be Dark
                ((6, 35, 0), ColorScheme::Light),  // after sunrise, should be Light
                ((12, 0, 0), ColorScheme::Light),  // noon, should be Light
                ((21, 00, 0), ColorScheme::Light), // before sunset, should be Light
                ((21, 30, 0), ColorScheme::Light), // after sunset, should be Dark
                ((23, 0, 0), ColorScheme::Dark),   // late night, should be Dark
            ],
        );
    }

    #[test]
    fn test_kenya_midday_night() {
        // Garissa County, Kenya
        test_location(
            0.3488742,
            40.1127608,
            2026,
            Month::December,
            1,
            "+03:00",
            &[
                ((5, 20, 0), ColorScheme::Dark),   // before sunrise, should be Dark
                ((6, 3, 0), ColorScheme::Light),   // after sunrise, should be Light
                ((12, 0, 0), ColorScheme::Light),  // noon, should be Light
                ((18, 10, 0), ColorScheme::Light), // before sunset, should be Light
                ((19, 00, 0), ColorScheme::Dark),  // after sunset, should be Dark
                ((23, 0, 0), ColorScheme::Dark),   // late night, should be Dark
            ],
        );
    }
}
