// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Basic application and environment information for the UI.
 */
export type AppInfo = { version: string, configDir: string, logDir: string, cacheDir: string, };
