// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A theme available for download (built-in) or already installed (custom).
 */
export type CatalogTheme = { id: string, name: string, 
/**
 * `"catalog"` (downloadable, remote thumbnails) or `"custom"` (installed
 * under the customized themes directory, local thumbnail paths).
 */
source: string, 
/**
 * Remote URLs for catalog themes; absolute local paths for custom themes.
 */
thumbnails: Array<string>, };
