// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A theme available for download.
 */
export type CatalogTheme = { id: string, name: string, thumbnails: Array<string>, };
