// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormat } from "./ImageFormat";
import type { Network } from "./Network";
import type { PositionSource } from "./PositionSource";
import type { WallpaperMode } from "./WallpaperMode";

export type Config = { 
/**
 * Network configuration for specifying a GitHub mirror template or SOCKS5 proxy.
 *
 * Only used in dwall-settings.
 */
network: Network | null, 
/**
 * Title bar follows the Windows theme color.
 *
 * By default, the program sets the same color as the window background. Users can manually disable this to use the Windows theme color.
 *
 * Only used in dwall-settings.
 */
title_bar_color_follows_windows_theme: boolean, image_format: ImageFormat, position_source: PositionSource, auto_detect_color_scheme: boolean, lock_screen_wallpaper_enabled: boolean, themes_directory: string, customized_themes_directory: string, 
/**
 * Wallpaper mode (Fixed or Random)
 */
wallpaper_mode: WallpaperMode, 
/**
 * Time interval for detecting solar altitude angle and azimuth angle
 * Measured in seconds, range: `[MIN_INTERVAL_SECONDS, MAX_INTERVAL_SECONDS]`
 */
interval: number, };
