// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormat } from "./ImageFormat";

/**
 * Metadata for a customized theme
 */
export type CustomizedThemeMetadata = { image_format: ImageFormat, theme_name: string, author: string, version: number, };
