// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageFormat } from "./ImageFormat";

/**
 * Customized theme information
 */
export type CustomizedTheme = { id: string, directory: string, 
/**
 * Prefer thumbnails, fall back to images if unavailable
 */
thumbnails: Array<string>, image_format: ImageFormat, theme_name: string, author: string, version: number, };
