// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Metadata = { rid: number, currentVersion: string, version: string, body: string | null, };
