// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PositionSource = { "type": "AUTOMATIC", update_on_each_calculation: boolean, cache_minutes: number, } | { "type": "MANUAL", latitude: number, longitude: number, altitude: number, };
