// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The theme drawn for a given local date in random mode.
 */
export type RandomSelection = { 
/**
 * Local date (`YYYY-MM-DD`) the theme was drawn for.
 */
date: string, themeId: string, };
