// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Apparent solar position (altitude and azimuth) at a given instant.
 */
export type SolarPosition = { altitude: number, azimuth: number, };
