// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A solar angle entry from a theme's `solar.json` or `theme.toml`.
 */
export type SolarAngle = { index: number, altitude: number, azimuth: number, };
