// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MonitorSpecificWallpapers } from "./MonitorSpecificWallpapers";

/**
 * 壁纸切换模式
 */
export type WallpaperMode = { "mode": "fixed", monitor_specific_wallpapers: MonitorSpecificWallpapers, } | { "mode": "random", 
/**
 * 随机池（None 表示使用所有可用主题）
 */
pool: Array<string> | null, };
