const images = {
  "Big Sur": [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/5.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/6.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/7.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur/8.avif",
  ],
  "Big Sur 1": [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/5.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/6.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/7.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/8.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/9.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/10.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/11.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/12.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/13.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/14.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/15.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/BigSur1/16.avif",
  ],
  Catalina: [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/5.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/6.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/7.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Catalina/8.avif",
  ],
  "Earth ISS": [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/5.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/6.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/7.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/8.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/9.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/10.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/11.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/12.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/13.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/14.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/15.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/EarthISS/16.avif",
  ],
  Mojave: [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/5.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/6.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/7.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/8.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/9.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/10.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/11.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/12.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/13.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/14.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/15.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/Mojave/16.avif",
  ],
  "Ventura Graphic": [
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/VenturaGraphic/1.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/VenturaGraphic/2.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/VenturaGraphic/3.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/VenturaGraphic/4.avif",
    "https://mirror.ghproxy.com/https://github.com/dwall-rs/dwall-assets/blob/main/thumbnails/VenturaGraphic/5.avif",
  ],
};

export const themes: ThemeItem[] = Object.entries(images)
  .map(([id, thumbnails]) => ({
    id,
    thumbnail: thumbnails,
  }))
  .sort((a, b) => (a.id > b.id ? 1 : -1));
